### ISSUE TITLE
cargo run -p ac-examples --example transfer_with_ws_client  --- Panic

### ISSUE THREAD

**Issue by blockcowboy** [scs/substrate-api-client#555] opened 2023-04-27 20:54 UTC
Other examples run but transfer Example crashes :

cargo run -p ac-examples --example transfer_with_ws_client RUST_BACKTRACE=1
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
warning: unused import: `frame_support::serde::__private::de::IdentifierDeserializer`
  --> examples/examples/transfer_with_ws_client.rs:18:5
   |
18 | use frame_support::serde::__private::de::IdentifierDeserializer;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: `ac-examples` (example "transfer_with_ws_client") generated 1 warning (run `cargo fix --example "transfer_with_ws_client"` to apply 1 suggestion)
    Finished dev [unoptimized + debuginfo] target(s) in 1.22s
     Running `target/debug/examples/transfer_with_ws_client RUST_BACKTRACE=1`
signer account: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
[+] Bob's Free Balance is is 1152921504606846976

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ~/substrate-api-client/src/extrinsic/balances.rs:79:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
(base) allenbailey@nbdi substrate-api-client % cargo run -p ac-examples --example transfer_with_ws_client
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on build directory
warning: unused import: `frame_support::serde::__private::de::IdentifierDeserializer`
  --> examples/examples/transfer_with_ws_client.rs:18:5
   |
18 | use frame_support::serde::__private::de::IdentifierDeserializer;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: `ac-examples` (example "transfer_with_ws_client") generated 1 warning (run `cargo fix --example "transfer_with_ws_client"` to apply 1 suggestion)
    Finished dev [unoptimized + debuginfo] target(s) in 8.54s
     Running `target/debug/examples/transfer_with_ws_client`
signer account: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
[+] Bob's Free Balance is is 1152921504606846976

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ~/substrate-api-client/src/extrinsic/balances.rs:79:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by haerdib** [comment] 2023-04-28 13:53
Hey @blockcowboy,

there's been a Substrate update recently, where they changed the balance transfer command. Maybe that's the problem?
So just to confirm:
- Are all transfer examples failing, or does the `transfer_with_tungstenite_client.rs` example pass?
- Which substrate-api-client version are you using? (branch, tag or commit?)
- Which node version are you running the api-client against? (polkadot branch? Or Substrate master on which commit?)

**Comment by blockcowboy** [comment] 2023-04-28 15:38
**Are all transfer examples failing, or does the transfer_with_tungstenite_client.rs example pass?**

Yes the other transfer fails:

% cargo run -p ac-examples --example transfer_with_tungstenite_client   
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on build directory
   Compiling ac-examples v0.3.0 (~/substrate-api-client/examples)
    Finished dev [unoptimized + debuginfo] target(s) in 10.01s
     Running `target/debug/examples/transfer_with_tungstenite_client`
signer account: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
[+] Bob's Free Balance is is 1152921504606846976

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ~/substrate-api-client/src/extrinsic/balances.rs:79:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Which substrate-api-client version are you using? (branch, tag or commit?)**

https://github.com/scs/substrate-api-client/tags
V0.11.0

**Which node version are you running the api-client against? (polkadot branch? Or Substrate master on which commit?)**

https://github.com/paritytech/substrate-contracts-node/tags
V0.24.0

**Comment by blockcowboy** [comment] 2023-04-28 15:45
FYI , Locan node balance transfer works with:

https://github.com/paritytech/polkadot-interaction-examples-rs

**Comment by haerdib** [comment] 2023-05-02 08:22
I looked into the nodes a little and I'm quite certain that the problem is a version mismatch:
 
- Substrate Contracts Node uses the Substrate version of polkadot-branch v0.9.37: See the [Cargo.lock](https://github.com/paritytech/substrate-contracts-node/blob/v0.24.0/Cargo.lock#L4071-L4084).
- The api-client tag v0.11.0 uses a newer version of Substrate, which has different Balances api. 

So I'd recommend using a matching api-client version, such as: https://github.com/scs/substrate-api-client/tree/polkadot-v0.9.37-tag-v0.10.0

There's no polkadot branch 0.9.37 for tag v0.11.0 yet. If that's necessary for your use case, we could release one. However, I'd recommend using a newer polkadot version either way, as Substrate is already at branch v0.9.42.

**Comment by blockcowboy** [comment] 2023-05-02 12:36
You may have a good point. Several people getting error with substrate-contracts-node :
 https://github.com/paritytech/substrate-contracts-node/issues/181

**Comment by blockcowboy** [comment] 2023-05-02 12:45
I checked Cargo.lock
source = "git+https://github.com/paritytech/substrate?branch=polkadot-v0.9.37#6fa7fe1326ecaab9921c2c3888530ad679cfbb87"

**Comment by haerdib** [comment] 2023-05-23 13:33
Hey @blockcowboy sorry for the delayed answer. I missed the follow-up question somehow. Are you referring to the `Cargo.toml` files of the api-client? 

And with tag, do you mean the api-client tag oder the polkadot branch name?

- If you're looking for a specific api-client tag and a polkadot branch, check out the [releases](https://github.com/scs/substrate-api-client/releases). There you find the tags and the available polkadot branches.
![grafik](https://github.com/scs/substrate-api-client/assets/73821294/4b545c3e-ab20-4f7c-b29d-f02231735f33)

- If you're already using a specific version and what to know which tag it is: check out the [`Cargo.toml`](https://github.com/scs/substrate-api-client/blob/master/Cargo.toml#L3). It specifies the last released tag. 

- If you want to refer to a specific polkadot branch, you can not use the `master` version of the api-client, as it points to Substrate master. Only the polkadot branches point to Substrate polkadot branches.

I hope somewhere in-between I have answered your question. If not, please let me know. Especially if something is missing in the api-clint releases.

**Comment by masapr** [comment] 2023-06-20 11:37
Hi @blockcowboy, can we close this issue?

**Comment by masapr** [comment] 2023-07-05 12:12
Closing issue due to inactivity, feel free to reopen if needed.

**Closed by masapr** 2023-07-05 12:12 UTC
Labels: F9-question
